In [1]:
import numpy as np
import pandas as pd
import datetime
from datetime import datetime, date
import matplotlib.pyplot as plt
%matplotlib inline

/opt/conda/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/opt/conda/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

In [2]:
df = pd.DataFrame(np.array([[23, 47],[45, 67]]), columns=['col1', 'col2'])
df

   col1  col2
0    23    47
1    45    67

In [4]:
len(df)

2

In [5]:
df.shape

(2, 2)

In [6]:
temp1 = [71, 90]
temp2 = [72, 100]
temp = {'temp1':temp1, 'temp2':temp2}
df = pd.DataFrame(temp)
df

   temp1  temp2
0     71     72
1     90    100

In [7]:
temp1 = pd.Series([71,90])
temp2 = pd.Series([90,100])
df = pd.DataFrame([temp1, temp2])
df.columns = ['temp1', 'temp2']
df

   temp1  temp2
0     71     90
1     90    100

In [8]:
temp1 = pd.Series([71,90])
temp2 = pd.Series([90,100])
df = pd.DataFrame({'temp1':temp1, 'temp2':temp2})
df

   temp1  temp2
0     71     90
1     90    100

In [9]:
df = pd.read_csv('grades.csv', index_col='student_id')
df.head()

,assignment1_grade,assignment1_submission,assignment2_grade,assignment2_submission,assignment3_grade,assignment3_submission,assignment4_grade,assignment4_submission,assignment5_grade,assignment5_submission,assignment6_grade,assignment6_submission
student_id,,,,,,,,,,,,
B73F2C11-70F0-E37D-8B10-1D20AFED50B1,92.733946,2015-11-02 06:55:34.282000000,83.030552,2015-11-09 02:22:58.938000000,67.164441,2015-11-12 08:58:33.998000000,53.011553,2015-11-16 01:21:24.663000000,47.710398,2015-11-20 13:24:59.692000000,38.168318,2015-11-22 18:31:15.934000000
98A0FAE0-A19A-13D2-4BB5-CFBFD94031D1,86.790821,2015-11-29 14:57:44.429000000,86.290821,2015-12-06 17:41:18.449000000,69.772657,2015-12-10 08:54:55.904000000,55.098125,2015-12-13 17:32:30.941000000,49.588313,2015-12-19 23:26:39.285000000,44.629482,2015-12-21 17:07:24.275000000
D0F62040-CEB0-904C-F563-2F8620916C4E,85.512541,2016-01-09 05:36:02.389000000,85.512541,2016-01-09 06:39:44.416000000,68.410033,2016-01-15 20:22:45.882000000,54.728026,2016-01-11 12:41:50.749000000,49.255224,2016-01-11 17:31:12.489000000,44.329701,2016-01-17 16:24:42.765000000
FFDF2B2C-F514-EF7F-6538-A6A53518E9DC,86.030665,2016-04-30 06:50:39.801000000,68.824532,2016-04-30 17:20:38.727000000,61.942079,2016-05-12 07:47:16.326000000,49.553663,2016-05-07 16:09:20.485000000,49.553663,2016-05-24 12:51:18.016000000,44.598297,2016-05-26 08:09:12.058000000
5ECBEEB6-F1CE-80AE-3164-E45E99473FB4,64.813800,2015-12-13 17:06:10.750000000,51.491040,2015-12-14 12:25:12.056000000,41.932832,2015-12-29 14:25:22.594000000,36.929549,2015-12-28 01:29:55.901000000,33.236594,2015-12-29 14:46:06.628000000,33.236594,2016-01-05 01:06:59.546000000

In [20]:
df.shape

(2315, 12)

In [21]:
len(df)

2315

In [23]:
df['assignment1_grade'].head()

student_id
B73F2C11-70F0-E37D-8B10-1D20AFED50B1    92.733946
98A0FAE0-A19A-13D2-4BB5-CFBFD94031D1    86.790821
D0F62040-CEB0-904C-F563-2F8620916C4E    85.512541
FFDF2B2C-F514-EF7F-6538-A6A53518E9DC    86.030665
5ECBEEB6-F1CE-80AE-3164-E45E99473FB4    64.813800
Name: assignment1_grade, dtype: float64

In [24]:
type(df['assignment1_grade'])

pandas.core.series.Series

In [25]:
df.assignment1_grade

student_id
B73F2C11-70F0-E37D-8B10-1D20AFED50B1     92.733946
98A0FAE0-A19A-13D2-4BB5-CFBFD94031D1     86.790821
D0F62040-CEB0-904C-F563-2F8620916C4E     85.512541
FFDF2B2C-F514-EF7F-6538-A6A53518E9DC     86.030665
5ECBEEB6-F1CE-80AE-3164-E45E99473FB4     64.813800
D09000A0-827B-C0FF-3433-BF8FF286E15B     71.647278
3217BE3F-E4B0-C3B6-9F64-462456819CE4     87.498744
F1CB5AA1-B3DE-5460-FAFF-BE951FD38B5F     80.576090
C9D51293-BD58-F113-4167-A7C0BAFCB6E5     66.595568
E2C617C2-4654-622C-AB50-1550C4BE42A0     59.270882
ECFE7BB7-F618-A5B9-7A57-3BD2BCC0D880     45.838780
B017B4A6-1F41-9D46-A040-21B0D270D4BE     76.670469
F2A4439C-F8D6-D47D-D884-C62E40366413     92.295151
8DC055F5-4B63-6CD1-9BAD-A2D927E01CDA     79.129632
35A9117B-9278-8C97-7180-DC1319117AB8     83.552847
24827B50-2FC2-E4B0-E2A0-1989E17749B3     14.959603
70A7A4AB-49ED-C587-D6E2-1518863B3411     42.299189
D6EFCCCA-82CA-C4BE-1C3E-D0477DE28B24     53.555227
15A04776-A6C6-72DC-B55F-A6A82B95E0B2     60.638097
C040D322-E970-4E8F-22A6-2FFAF2D74061     36.383575
D5E03B6F-E4AB-AD56-FCB5-12ACA02D3622     82.478383
E03DE248-3570-3C31-77F7-5138764837A6     73.198584
A1331E62-50B5-94FC-E0CE-3092CB3D30D9     88.901114
4D914022-B7D7-52C4-A1BB-479166DB7347     99.886995
FCB5854D-D84C-E8BA-4AF8-59FCF9CC69CB     88.700055
A4FB423A-E08E-559F-DCCD-A0A543E812E3     73.256087
D887D9D7-6993-7618-5333-1DBC732CAA5E     81.471342
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31     75.756429
DDE0526B-7DA4-80E8-C2A6-D097F3826029     94.437504
DE88902E-C7A7-E37A-CFA7-F2C8F2D219F2     90.868490
                                           ...
DE88902E-C7A7-E37A-CFA7-F2C8F2D219F2     99.467096
25197F10-E9E9-4C50-63F8-6C896975AAE2     95.655352
DDE0526B-7DA4-80E8-C2A6-D097F3826029     58.181599
DDE0526B-7DA4-80E8-C2A6-D097F3826029    100.009744
5AB0D44C-86FF-2DE6-B096-B0F5D029E430     84.266188
247B105C-2067-A7AA-2CBE-B65278128C96     82.464507
2B806EF6-A590-1C00-F0C5-1469E3B2152E     92.912163
DE88902E-C7A7-E37A-CFA7-F2C8F2D219F2     79.229081
6D2AB78F-44F4-2E8B-5C5E-B79119BC7EAC     60.301026
DDE0526B-7DA4-80E8-C2A6-D097F3826029     75.499444
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31     38.788636
25197F10-E9E9-4C50-63F8-6C896975AAE2     74.106685
25197F10-E9E9-4C50-63F8-6C896975AAE2     91.192781
DDE0526B-7DA4-80E8-C2A6-D097F3826029     68.571967
247B105C-2067-A7AA-2CBE-B65278128C96     58.760286
1F51E050-78F7-F270-1B90-ED1BC0376763     88.777948
25197F10-E9E9-4C50-63F8-6C896975AAE2     74.260083
2B806EF6-A590-1C00-F0C5-1469E3B2152E     62.048275
DDE0526B-7DA4-80E8-C2A6-D097F3826029     97.215052
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31     65.123101
5AB0D44C-86FF-2DE6-B096-B0F5D029E430     76.819524
DDE0526B-7DA4-80E8-C2A6-D097F3826029     47.696703
1F51E050-78F7-F270-1B90-ED1BC0376763     94.595758
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31     71.481182
6D2AB78F-44F4-2E8B-5C5E-B79119BC7EAC     82.640274
DE88902E-C7A7-E37A-CFA7-F2C8F2D219F2     77.684611
DE88902E-C7A7-E37A-CFA7-F2C8F2D219F2     75.367870
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31     73.269463
1F51E050-78F7-F270-1B90-ED1BC0376763     87.268366
DDE0526B-7DA4-80E8-C2A6-D097F3826029     80.318105
Name: assignment1_grade, dtype: float64

In [28]:
df.loc[['EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31', 'DDE0526B-7DA4-80E8-C2A6-D097F3826029']]

,assignment1_grade,assignment1_submission,assignment2_grade,assignment2_submission,assignment3_grade,assignment3_submission,assignment4_grade,assignment4_submission,assignment5_grade,assignment5_submission,assignment6_grade,assignment6_submission
student_id,,,,,,,,,,,,
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,75.756429,2015-09-18 20:18:12.171000000,75.256429,2015-09-29 20:18:02.673000000,75.956429,2015-10-10 15:11:56.910000000,60.045143,2015-09-30 23:19:46.018000000,54.040629,2015-10-12 00:42:54.909000000,54.040629,2015-12-10 21:25:50.740000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,70.211257,2016-08-05 12:13:24.333000000,63.190131,2016-08-08 13:55:01.837000000,56.871118,2016-08-10 13:11:18.342000000,45.496894,2016-08-15 06:20:36.336000000,36.397516,2016-08-17 09:44:31.612000000,36.397516,2016-08-26 14:40:12.755000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,68.723308,2015-10-30 19:31:08.332000000,61.420977,2015-11-06 19:42:51.117000000,55.998880,2015-11-15 01:58:36.636000000,55.098880,2015-11-12 19:49:56.650000000,44.079104,2015-11-20 02:56:15.080000000,44.079104,2015-11-28 01:46:18.249000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,57.362777,2016-01-10 10:52:57.450000000,57.362777,2016-01-16 03:33:05.322000000,45.890221,2016-01-22 16:53:51.770000000,41.301199,2016-01-21 14:14:36.907000000,41.301199,2016-01-21 14:52:23.819000000,37.171079,2016-02-02 10:02:35.633000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,81.897256,2016-06-22 22:06:14.219000000,81.897256,2016-06-27 12:52:45.217000000,65.517805,2016-07-03 04:48:57.211000000,65.517805,2016-07-05 07:54:19.959000000,58.966024,2016-07-11 07:32:08.963000000,47.172819,2016-07-13 20:48:01.719000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,83.817497,2015-09-15 10:54:38.433000000,83.317497,2015-09-16 08:26:26.150000000,84.017497,2015-09-18 21:18:32.592000000,83.117497,2015-09-16 13:17:41.987000000,66.493998,2015-09-17 12:55:44.866000000,66.493998,2015-09-18 21:18:33.685000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,84.767391,2016-08-05 14:46:26.174000000,67.813913,2016-08-10 06:08:46.059000000,54.251130,2016-08-12 12:17:53.646000000,54.251130,2016-08-18 12:46:56.824000000,54.251130,2016-08-26 13:11:25.842000000,48.826017,2016-08-27 20:35:37.491000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,77.932352,2015-09-19 13:05:33.801000000,77.432352,2015-09-19 13:08:52.007000000,70.409117,2015-09-17 22:45:59.416000000,69.509117,2015-09-19 13:15:57.079000000,69.509117,2015-09-19 13:27:30.929000000,55.607293,2015-09-17 21:38:00.615000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,81.217717,2015-11-28 02:31:14.544000000,72.665945,2015-12-03 18:22:28.836000000,73.365945,2015-12-08 12:24:55.431000000,65.219351,2015-12-07 21:45:20.648000000,52.175481,2015-12-17 13:23:30.480000000,52.175481,2015-12-20 21:11:11.127000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,61.042544,2015-12-19 23:37:24.528000000,48.474036,2015-12-21 00:33:00.082000000,39.519228,2015-12-24 01:02:11.311000000,38.619228,2016-02-22 10:55:03.044000000,30.895383,2016-03-02 13:52:29.171000000,24.716306,2016-03-03 08:31:33.718000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,72.549940,2016-04-21 21:35:24.020000000,65.294946,2016-04-23 22:43:05.561000000,58.765452,2016-04-26 15:56:53.289000000,52.888907,2016-05-02 19:55:02.777000000,52.888907,2016-05-03 16:25:51.477000000,42.311125,2016-05-07 19:18:58.435000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,69.522925,2016-01-24 13:55:35.204000000,69.522925,2016-01-29 20:19:24.805000000,69.522925,2016-01-31 12:35:20.816000000,55.618340,2016-02-06 18:33:25.888000000,55.618340,2016-02-13 17:00:44.274000000,50.056506,2016-02-14 17:44:00.212000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,87.845625,2016-01-10 13:58:08.170000000,87.845625,2016-01-12 13:07:03.733000000,70.276500,2016-01-17 16:24:38.003000000,63.248850,2016-01-16 19:44:53.784000000,63.248850,2016-01-30 15:29:14.570000000,56.923965,2016-01-31 17:42:24.152000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,77.480784,2015-10-18 20:16:13.080000000,76.980784,2015-10-21 22:03:45.355000000,70.002706,2015-10-27 21:33:55.839000000,69.102706,2015-11-01 21:03:19.240000000,55.282165,2015-11-06 22:45:05.072000000,55.282165,2015-11-11 02:28:42.081000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,65.127708,2015-10-19 19:57:39.766000000,64.627708,2015-10-26 21:36:27.645000000,65.327708,2015-10-30 16:27:00.932000000,51.542166,2015-10-30 22:47:07.362000000,46.387949,2015-11-08 15:13:11.638000000,46.387949,2015-11-30 23:55:31.415000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,60.684850,2016-01-24 12:21:41.547000000,54.616365,2016-01-30 06:52:54.155000000,49.154729,2016-02-02 05:33:41.952000000,49.154729,2016-02-11 15:06:31.662000000,39.323783,2016-02-13 15:32:35.804000000,39.323783,2016-02-15 10:36:30.556000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,88.614537,2015-10-18 03:53:16.188000000,79.323083,2015-10-25 06:11:43.947000000,64.198466,2015-10-28 17:01:29.530000000,56.968620,2015-11-01 19:40:31.031000000,51.271758,2015-11-09 02:15:06.286000000,51.271758,2015-11-11 20:57:07.528000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,72.355294,2016-04-15 16:23:14.865000000,57.884235,2016-04-16 02:37:58.922000000,57.884235,2016-04-28 07:46:11.471000000,52.095812,2016-04-16 13:41:44.230000000,41.676649,2016-04-27 21:49:41.179000000,37.508985,2016-05-03 15:01:12.915000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,85.725458,2015-12-11 13:17:16.063000000,85.225458,2015-12-16 13:09:15.972000000,77.422912,2015-12-22 10:33:46.448000000,68.870621,2015-12-24 13:23:11.663000000,68.870621,2015-12-29 14:01:17.518000000,55.096496,2016-01-10 21:56:04.592000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,96.208582,2016-01-05 09:20:20.215000000,76.966865,2016-01-12 11:27:48.981000000,69.270179,2016-01-19 17:54:58.241000000,62.343161,2016-01-24 06:10:42.316000000,49.874529,2016-01-29 21:16:25.557000000,39.899623,2016-02-01 08:35:49.697000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,97.769445,2015-10-17 16:07:45.067000000,77.855556,2015-10-21 13:16:39.117000000,70.790000,2015-10-28 02:04:28.743000000,62.901000,2015-10-28 01:34:53.214000000,62.901000,2015-10-31 11:21:00.641000000,56.610900,2015-11-05 10:54:39.587000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,76.613318,2016-04-09 05:14:53.253000000,68.951987,2016-04-09 17:37:14.851000000,55.161589,2016-04-11 22:39:58.663000000,44.129271,2016-04-15 23:40:12.027000000,39.716344,2016-04-19 01:01:13.800000000,39.716344,2016-04-28 03:48:11.990000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,67.050365,2015-09-21 02:46:13.680000000,66.550365,2015-09-27 18:10:06.015000000,60.615328,2015-10-13 20:10:03.521000000,47.772263,2015-10-05 01:58:23.707000000,42.995036,2015-10-05 02:17:07.722000000,42.995036,2015-10-15 14:21:08.597000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,72.750129,2016-03-01 14:05:11.663000000,72.750129,2016-03-07 15:42:26.721000000,58.200104,2016-03-17 07:30:09.271000000,52.380093,2016-03-17 13:29:08.426000000,41.904075,2016-03-18 12:36:24.369000000,37.713667,2016-03-31 03:05:19.199000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,85.653818,2015-11-15 09:35:51.544000000,85.153818,2015-11-21 13:40:30.436000000,85.853818,2016-01-05 04:07:23.324000000,84.953818,2015-11-28 18:55:38.767000000,76.458436,2015-12-07 02:35:44.318000000,61.166749,2015-12-10 08:54:59.513000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,98.912367,2016-01-09 03:17:54.117000000,89.021130,2016-01-14 18:28:45.977000000,80.119017,2016-01-19 21:24:07.696000000,80.119017,2016-01-21 22:13:43.754000000,64.095214,2016-01-27 22:47:16.634000000,51.276171,2016-01-30 23:33:29.258000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,30.789082,2015-10-17 20:15:09.431000000,24.271265,2015-10-25 14:59:37.761000000,20.157012,2015-10-28 03:03:49.887000000,15.405610,2015-11-01 17:04:27.367000000,12.324488,2015-11-09 15:37:53.627000000,11.092039,2015-11-12 08:58:39.041000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,61.605867,2015-11-01 16:39:18.967000000,55.015281,2015-11-01 16:58:18.249000000,50.233752,2016-01-30 06:58:47.851000000,44.400377,2015-11-01 17:21:30.905000000,44.400377,2015-11-01 21:27:15.265000000,44.400377,2016-02-05 11:49:48.513000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,75.213380,2015-10-04 15:26:55.249000000,74.713380,2015-10-07 03:57:16.551000000,67.962042,2015-10-13 01:11:41.144000000,53.649634,2015-10-16 07:09:38.960000000,53.649634,2015-10-25 08:14:20.798000000,48.284670,2015-10-26 08:06:09.787000000
EFDA9F93-D0C3-864F-B0F6-2E9AA3E05E31,82.353088,2015-12-12 01:59:15.922000000,73.687779,2015-12-20 04:38:10.866000000,74.387779,2015-12-23 03:32:13.743000000,66.139001,2015-12-27 23:40:06.694000000,59.525101,2015-12-31 18:23:05.760000000,59.525101,2016-01-07 17:33:20.887000000
...,...,...,...,...,...,...,...,...,...,...,...,...
DDE0526B-7DA4-80E8-C2A6-D097F3826029,48.969599,2016-01-11 06:18:38.192000000,48.969599,2016-01-18 07:11:32.148000000,39.175679,2016-01-21 08:53:25.223000000,35.258111,2016-02-08 06:13:54.761000000,35.258111,2016-02-01 07:27:02.613000000,28.206489,2016-02-02 08:03:22.229000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,85.217200,2016-03-31 00:14:17.214000000,76.695480,2016-04-05 04:47:08.581000000,69.025932,2016-04-12 03:16:53.066000000,55.220745,2016-04-14 02:13:54.292000000,55.220745,2016-04-22 05:23:55.478000000,44.176596,2016-04-25 20:56:02.272000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,93.605455,2016-05-29 22:56:36.556000000,93.605455,2016-06-05 20:07:32.967000000,84.244910,2016-06-09 07:30:31.411000000,84.244910,2016-06-19 15:08:01.213000000,75.820419,2016-06-19 18:02:41.859000000,68.238377,2016-06-21 04:32:43.196000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,48.048311,2016-01-07 07:38:21.810000000,38.438649,2016-01-20 08:53:47.259000000,30.750919,2016-03-03 08:31:29.033000000,30.750919,2016-02-03 10:29:43.831000000,24.600735,2016-03-02 09:41:00.783000000,19.680588,2016-03-11 16:34:34.730000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,66.752452,2016-05-29 23:44:52.155000000,66.752452,2016-06-03 22:42:52.868000000,60.077206,2016-06-08 00:26:38.201000000,48.061765,2016-06-12 17:53:51.175000000,38.449412,2016-06-19 14:48:56.910000000,30.759530,2016-06-23 07:54:40.655000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,55.404548,2015-10-04 21:23:13.316000000,43.963639,2015-10-09 23:01:09.825000000,44.663639,2015-10-12 22:37:37.203000000,35.010911,2015-10-18 22:23:28.846000000,28.008729,2015-10-25 16:34:16.893000000,28.008729,2015-10-27 03:31:14.395000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,81.307920,2016-07-08 11:13:19.128000000,65.046336,2016-07-23 08:02:17.448000000,58.541702,2016-07-29 21:17:42.978000000,52.687532,2016-07-24 00:06:36.587000000,47.418779,2016-07-28 08:24:15.993000000,47.418779,2016-07-31 21:18:04.565000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,78.248660,2016-03-20 13:56:13.177000000,70.423794,2016-03-25 12:54:19.855000000,56.339035,2016-03-29 19:40:10.052000000,56.339035,2016-03-31 13:27:32.353000000,45.071228,2016-04-02 11:15:33.567000000,40.564105,2016-04-10 06:41:33.070000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,80.139264,2016-07-06 17:17:46.311000000,72.125338,2016-07-07 18:53:51.581000000,72.125338,2016-07-24 20:17:50.619000000,57.700270,2016-07-08 05:49:28.850000000,51.930243,2016-07-09 01:08:00.158000000,46.737219,2016-07-25 16:48:03.986000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,97.921008,2016-01-10 23:14:37.659000000,97.921008,2016-01-17 22:12:42.469000000,78.336807,2016-01-21 03:24:26.516000000,62.669445,2016-01-31 12:57:35.801000000,50.135556,2016-01-31 21:56:48.843000000,45.122001,2016-02-01 22:37:27.188000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,82.388956,2016-02-07 19:16:07.596000000,65.911165,2016-02-11 18:43:58.674000000,65.911165,2016-02-18 08:34:57.716000000,59.320049,2016-02-22 04:06:51.965000000,53.388044,2016-02-27 17:52:42.670000000,53.388044,2016-02-29 23:09:43.037000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,67.328963,2015-12-26 13:26:04.642000000,60.166067,2016-01-02 18:53:45.950000000,54.869460,2016-01-04 15:42:14.229000000,53.969460,2016-01-10 16:30:07.673000000,53.969460,2016-01-15 12:10:23.744000000,48.572514,2016-01-19 03:54:54.607000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,35.528671,2016-01-10 08:14:38.598000000,28.422936,2016-01-17 11:06:42.313000000,22.738349,2016-01-20 05:52:47.157000000,18.190679,2016-02-07 09:12:41.418000000,14.552543,2016-02-14 09:16:06.120000000,13.097289,2016-02-15 10:36:30.500000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,78.954273,2015-10-03 16:51:34.001000000,78.454273,2015-10-04 16:30:22.945000000,63.503418,2015-10-05 19:04:10.928000000,50.082735,2015-10-19 02:54:34.274000000,40.066188,2015-10-25 14:20:48.983000000,32.052950,2015-10-26 18:34:16.495000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,61.483230,2016-07-20 03:33:20.294000000,49.186584,2016-07-20 09:44:42.728000000,44.267926,2016-08-01 06:17:59.270000000,44.267926,2016-07-23 21:07:47.781000000,39.841133,2016-07-24 18:47:30.383000000,39.841133,2016-08-16 01:35:52.967000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,62.363434,2016-07-01 16:59:02.002000000,56.127090,2016-07-16 23:44:04.955000000,44.901672,2016-07-23 20:21:44.630000000,44.901672,2016-07-23 19:43:05.359000000,40.411505,2016-07-31 20:31:39.280000000,40.411505,2016-08-04 07:48:46.214000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,80.431853,2015-09-20 17:21:37.660000000,71.958668,2015-09-24 19:32:34.917000000,72.658668,2015-10-09 21:50:11.544000000,71.758668,2015-10-02 22:47:26.203000000,57.406934,2015-10-09 17:15:47.678000000,51.666241,2015-10-15 18:31:54.138000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,93.145001,2015-10-02 14:19:41.921000000,92.645001,2015-10-02 16:26:09.357000000,93.345001,2015-10-07 00:37:38.774000000,92.445001,2015-10-04 16:23:01.877000000,92.445001,2015-10-06 01:31:29.739000000,92.445001,2015-10-18 06:29:23.646000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,64.347594,2015-11-29 22:12:17.053000000,63.847594,2015-12-06 22:06:36.872000000,64.547594,2016-03-01 00:46:46.797000000,57.282835,2015-12-21 18:27:51.422000000,51.554551,2015-12-24 22:16:25.060000000,46.399096,2016-03-01 11:15:32.548000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,68.359982,2015-09-20 17:07:17.190000000,61.093984,2015-09-26 18:52:54.522000000,49.615187,2015-09-30 04:53:52.788000000,43.843668,2015-10-03 22:38:25.863000000,35.074935,2015-10-10 21:51:03.215000000,35.074935,2015-10-11 23:10:04.566000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,86.696265,2015-12-28 03:46:50.474000000,68.997012,2016-01-01 03:42:34.115000000,69.697012,2016-01-07 08:55:44.092000000,61.917310,2016-01-09 03:14:29.375000000,49.533848,2016-01-17 18:45:40.375000000,39.627079,2016-01-20 17:54:08.680000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,86.824217,2015-09-19 22:12:32.304000000,69.099374,2015-09-27 21:13:49.648000000,62.909436,2015-09-30 02:24:59.422000000,49.607549,2015-10-04 22:12:11.506000000,49.607549,2015-10-12 03:16:14.931000000,44.646794,2015-10-13 03:44:10.281000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,78.438381,2015-12-14 05:10:49.343000000,77.938381,2015-12-21 06:25:19.560000000,70.864543,2015-12-24 08:32:51.190000000,69.964543,2016-01-04 03:02:45.928000000,69.964543,2016-01-04 03:11:40.725000000,69.964543,2016-07-09 05:49:05.759000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,58.181599,2016-01-07 04:16:27.258000000,52.363439,2016-01-09 23:35:53.020000000,41.890752,2016-01-19 21:24:08.081000000,37.701676,2016-01-10 15:42:26.688000000,33.931509,2016-01-11 02:28:48.528000000,33.931509,2016-02-04 00:44:23.751000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,100.009744,2015-10-18 22:08:01.298000000,79.647795,2015-10-26 03:14:55.856000000,64.458236,2015-10-28 22:03:28.868000000,57.202413,2015-11-01 15:48:02.103000000,45.761930,2015-11-07 20:59:41.986000000,36.609544,2015-11-12 02:58:56.525000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,75.499444,2015-11-01 15:41:55.707000000,60.039556,2015-11-08 21:37:21.087000000,54.755600,2015-11-12 04:57:30.730000000,43.084480,2015-11-14 11:34:40.193000000,43.084480,2015-11-22 13:13:04.751000000,34.467584,2015-11-25 01:47:19.956000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,68.571967,2016-01-24 02:07:02.216000000,61.714770,2016-01-30 03:35:47.727000000,49.371816,2016-01-31 20:15:38.336000000,39.497453,2016-02-02 06:00:17.713000000,31.597962,2016-02-10 06:00:25.069000000,25.278370,2016-02-12 23:47:21.212000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,97.215052,2016-01-23 09:19:40.494000000,77.772041,2016-01-26 08:38:13.085000000,69.994837,2016-01-29 15:04:34.705000000,62.995353,2016-02-06 12:51:00.647000000,50.396283,2016-02-11 15:44:08.113000000,50.396283,2016-02-14 09:03:33.466000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,47.696703,2016-06-22 20:21:58.182000000,38.157363,2016-06-23 18:22:45.622000000,38.157363,2016-07-02 22:18:59.529000000,30.525890,2016-06-28 22:05:38.100000000,30.525890,2016-07-09 20:08:14.734000000,30.525890,2016-07-17 15:17:58.502000000
DDE0526B-7DA4-80E8-C2A6-D097F3826029,80.318105,2015-10-04 09:46:03.403000000,79.818105,2015-10-06 10:28:30.820000000,64.594484,2015-10-13 17:06:29.179000000,50.955587,2015-10-06 16:18:35.513000000,40.764470,2015-10-23 17:03:26.939000000,40.764470,2015-10-26 15:56:55.460000000

In [30]:
df.iloc[[0,2]]

,assignment1_grade,assignment1_submission,assignment2_grade,assignment2_submission,assignment3_grade,assignment3_submission,assignment4_grade,assignment4_submission,assignment5_grade,assignment5_submission,assignment6_grade,assignment6_submission
student_id,,,,,,,,,,,,
B73F2C11-70F0-E37D-8B10-1D20AFED50B1,92.733946,2015-11-02 06:55:34.282000000,83.030552,2015-11-09 02:22:58.938000000,67.164441,2015-11-12 08:58:33.998000000,53.011553,2015-11-16 01:21:24.663000000,47.710398,2015-11-20 13:24:59.692000000,38.168318,2015-11-22 18:31:15.934000000
D0F62040-CEB0-904C-F563-2F8620916C4E,85.512541,2016-01-09 05:36:02.389000000,85.512541,2016-01-09 06:39:44.416000000,68.410033,2016-01-15 20:22:45.882000000,54.728026,2016-01-11 12:41:50.749000000,49.255224,2016-01-11 17:31:12.489000000,44.329701,2016-01-17 16:24:42.765000000

In [32]:
i1 = df.index.get_loc('98A0FAE0-A19A-13D2-4BB5-CFBFD94031D1')
i2 = df.index.get_loc('D09000A0-827B-C0FF-3433-BF8FF286E15B')
(i1,i2)

(1, 5)

In [33]:
df.iloc[[i1,i2]]

,assignment1_grade,assignment1_submission,assignment2_grade,assignment2_submission,assignment3_grade,assignment3_submission,assignment4_grade,assignment4_submission,assignment5_grade,assignment5_submission,assignment6_grade,assignment6_submission
student_id,,,,,,,,,,,,
98A0FAE0-A19A-13D2-4BB5-CFBFD94031D1,86.790821,2015-11-29 14:57:44.429000000,86.290821,2015-12-06 17:41:18.449000000,69.772657,2015-12-10 08:54:55.904000000,55.098125,2015-12-13 17:32:30.941000000,49.588313,2015-12-19 23:26:39.285000000,44.629482,2015-12-21 17:07:24.275000000
D09000A0-827B-C0FF-3433-BF8FF286E15B,71.647278,2015-12-28 04:35:32.836000000,64.052550,2016-01-03 21:05:38.392000000,64.752550,2016-01-07 08:55:43.692000000,57.467295,2016-01-11 00:45:28.706000000,57.467295,2016-01-11 00:54:13.579000000,57.467295,2016-01-20 19:54:46.166000000

In [35]:
df.at['98A0FAE0-A19A-13D2-4BB5-CFBFD94031D1','assignment1_grade']

86.790820857929859

In [37]:
df.iat[0, 0]

92.73394640624123

In [43]:
df[:5]

,assignment1_grade,assignment1_submission,assignment2_grade,assignment2_submission,assignment3_grade,assignment3_submission,assignment4_grade,assignment4_submission,assignment5_grade,assignment5_submission,assignment6_grade,assignment6_submission
student_id,,,,,,,,,,,,
B73F2C11-70F0-E37D-8B10-1D20AFED50B1,92.733946,2015-11-02 06:55:34.282000000,83.030552,2015-11-09 02:22:58.938000000,67.164441,2015-11-12 08:58:33.998000000,53.011553,2015-11-16 01:21:24.663000000,47.710398,2015-11-20 13:24:59.692000000,38.168318,2015-11-22 18:31:15.934000000
98A0FAE0-A19A-13D2-4BB5-CFBFD94031D1,86.790821,2015-11-29 14:57:44.429000000,86.290821,2015-12-06 17:41:18.449000000,69.772657,2015-12-10 08:54:55.904000000,55.098125,2015-12-13 17:32:30.941000000,49.588313,2015-12-19 23:26:39.285000000,44.629482,2015-12-21 17:07:24.275000000
D0F62040-CEB0-904C-F563-2F8620916C4E,85.512541,2016-01-09 05:36:02.389000000,85.512541,2016-01-09 06:39:44.416000000,68.410033,2016-01-15 20:22:45.882000000,54.728026,2016-01-11 12:41:50.749000000,49.255224,2016-01-11 17:31:12.489000000,44.329701,2016-01-17 16:24:42.765000000
FFDF2B2C-F514-EF7F-6538-A6A53518E9DC,86.030665,2016-04-30 06:50:39.801000000,68.824532,2016-04-30 17:20:38.727000000,61.942079,2016-05-12 07:47:16.326000000,49.553663,2016-05-07 16:09:20.485000000,49.553663,2016-05-24 12:51:18.016000000,44.598297,2016-05-26 08:09:12.058000000
5ECBEEB6-F1CE-80AE-3164-E45E99473FB4,64.813800,2015-12-13 17:06:10.750000000,51.491040,2015-12-14 12:25:12.056000000,41.932832,2015-12-29 14:25:22.594000000,36.929549,2015-12-28 01:29:55.901000000,33.236594,2015-12-29 14:46:06.628000000,33.236594,2016-01-05 01:06:59.546000000

In [45]:
df['98A0FAE0-A19A-13D2-4BB5-CFBFD94031D1':'5ECBEEB6-F1CE-80AE-3164-E45E99473FB4']

,assignment1_grade,assignment1_submission,assignment2_grade,assignment2_submission,assignment3_grade,assignment3_submission,assignment4_grade,assignment4_submission,assignment5_grade,assignment5_submission,assignment6_grade,assignment6_submission
student_id,,,,,,,,,,,,
98A0FAE0-A19A-13D2-4BB5-CFBFD94031D1,86.790821,2015-11-29 14:57:44.429000000,86.290821,2015-12-06 17:41:18.449000000,69.772657,2015-12-10 08:54:55.904000000,55.098125,2015-12-13 17:32:30.941000000,49.588313,2015-12-19 23:26:39.285000000,44.629482,2015-12-21 17:07:24.275000000
D0F62040-CEB0-904C-F563-2F8620916C4E,85.512541,2016-01-09 05:36:02.389000000,85.512541,2016-01-09 06:39:44.416000000,68.410033,2016-01-15 20:22:45.882000000,54.728026,2016-01-11 12:41:50.749000000,49.255224,2016-01-11 17:31:12.489000000,44.329701,2016-01-17 16:24:42.765000000
FFDF2B2C-F514-EF7F-6538-A6A53518E9DC,86.030665,2016-04-30 06:50:39.801000000,68.824532,2016-04-30 17:20:38.727000000,61.942079,2016-05-12 07:47:16.326000000,49.553663,2016-05-07 16:09:20.485000000,49.553663,2016-05-24 12:51:18.016000000,44.598297,2016-05-26 08:09:12.058000000
5ECBEEB6-F1CE-80AE-3164-E45E99473FB4,64.813800,2015-12-13 17:06:10.750000000,51.491040,2015-12-14 12:25:12.056000000,41.932832,2015-12-29 14:25:22.594000000,36.929549,2015-12-28 01:29:55.901000000,33.236594,2015-12-29 14:46:06.628000000,33.236594,2016-01-05 01:06:59.546000000

In [23]:
sp500 = pd.read_csv('sp500.csv', index_col='Symbol',usecols=[0,2,3,7])
sp500

                             Sector   Price  Book Value
Symbol
MMM                     Industrials  141.14      26.668
ABT                     Health Care   39.60      15.573
ABBV                    Health Care   53.95       2.954
ACN          Information Technology   79.79       8.326
ACE                      Financials  102.91      86.897
ACT                     Health Care  213.77      55.188
ADBE         Information Technology   64.30      13.262
AES                       Utilities   13.61       5.781
AET                     Health Care   76.39      40.021
AFL                      Financials   61.31      34.527
A                       Health Care   56.18      16.928
GAS                       Utilities   52.98      32.462
APD                       Materials  118.74      34.723
ARG                       Materials  105.66      24.882
AKAM         Information Technology   53.65      15.193
AA                        Materials   13.52       9.670
ALXN                    Health Care  162.30      13.628
ATI                       Materials   40.99      26.401
ALLE                    Industrials   52.46       0.000
AGN                     Health Care  166.92      22.207
ADS          Information Technology  248.88      17.392
ALL                      Financials   58.38      47.465
ALTR         Information Technology   33.31      11.026
MO                 Consumer Staples   40.68       2.072
AMZN         Consumer Discretionary  312.24      22.452
AEE                       Utilities   38.64      26.847
AEP                       Utilities   51.41      33.635
AXP                      Financials   88.78      18.846
AIG                      Financials   53.60      71.775
AMT                      Financials   88.41       9.279
...                             ...     ...         ...
VIAB         Consumer Discretionary   84.99      10.253
V            Information Technology  212.07      43.391
VNO                      Financials  105.32      28.243
VMC                       Materials   61.19      30.819
WMT                Consumer Staples   75.61      22.607
WAG                Consumer Staples   69.79      21.779
DIS          Consumer Discretionary   83.32      26.405
WM                      Industrials   43.37      12.330
WAT                     Health Care  100.54      21.460
WLP                     Health Care  108.82      86.358
WFC                      Financials   50.16      30.479
WDC          Information Technology   84.83      37.311
WU           Information Technology   15.77       1.981
WY                       Financials   30.87      11.690
WHR          Consumer Discretionary  147.26      66.221
WFM                Consumer Staples   37.78      10.867
WIN     Telecommunications Services    9.38       1.199
WEC                       Utilities   45.13      19.165
WYN          Consumer Discretionary   72.22      11.984
WYNN         Consumer Discretionary  207.86      -0.719
XEL                       Utilities   30.24      19.450
XRX          Information Technology   12.06      10.471
XLNX         Information Technology   46.03      10.247
XL                       Financials   32.47      37.451
XYL                     Industrials   38.42      12.127
YHOO         Information Technology   35.02      12.768
YUM          Consumer Discretionary   74.77       5.147
ZMH                     Health Care  101.84      37.181
ZION                     Financials   28.43      30.191
ZTS                     Health Care   30.53       2.150

[500 rows x 3 columns]

In [11]:
sp500.index

Index(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ACT', 'ADBE', 'AES', 'AET', 'AFL',
       ...
       'XEL', 'XRX', 'XLNX', 'XL', 'XYL', 'YHOO', 'YUM', 'ZMH', 'ZION', 'ZTS'],
      dtype='object', name='Symbol', length=500)

In [12]:
sp500.columns

Index(['Sector', 'Price', 'Book Value'], dtype='object')

In [13]:
sp500['Sector'].head()

Symbol
MMM                Industrials
ABT                Health Care
ABBV               Health Care
ACN     Information Technology
ACE                 Financials
Name: Sector, dtype: object

In [14]:
sp500[['Sector','Price']].head()

                        Sector   Price
Symbol
MMM                Industrials  141.14
ABT                Health Care   39.60
ABBV               Health Care   53.95
ACN     Information Technology   79.79
ACE                 Financials  102.91

In [51]:
sp500.Price

Symbol
MMM     141.14
ABT      39.60
ABBV     53.95
ACN      79.79
ACE     102.91
ACT     213.77
ADBE     64.30
AES      13.61
AET      76.39
AFL      61.31
A        56.18
GAS      52.98
APD     118.74
ARG     105.66
AKAM     53.65
AA       13.52
ALXN    162.30
ATI      40.99
ALLE     52.46
AGN     166.92
ADS     248.88
ALL      58.38
ALTR     33.31
MO       40.68
AMZN    312.24
AEE      38.64
AEP      51.41
AXP      88.78
AIG      53.60
AMT      88.41
         ...
VIAB     84.99
V       212.07
VNO     105.32
VMC      61.19
WMT      75.61
WAG      69.79
DIS      83.32
WM       43.37
WAT     100.54
WLP     108.82
WFC      50.16
WDC      84.83
WU       15.77
WY       30.87
WHR     147.26
WFM      37.78
WIN       9.38
WEC      45.13
WYN      72.22
WYNN    207.86
XEL      30.24
XRX      12.06
XLNX     46.03
XL       32.47
XYL      38.42
YHOO     35.02
YUM      74.77
ZMH     101.84
ZION     28.43
ZTS      30.53
Name: Price, dtype: float64

In [54]:
sp500.loc[['MMM','YHOO']]

                        Sector   Price  Book Value
Symbol
MMM                Industrials  141.14      26.668
YHOO    Information Technology   35.02      12.768

In [56]:
sp500.iloc[[0, 3]]

                        Sector   Price  Book Value
Symbol
MMM                Industrials  141.14      26.668
ACN     Information Technology   79.79       8.326

In [57]:
sp500.Price < 100

Symbol
MMM     False
ABT      True
ABBV     True
ACN      True
ACE     False
ACT     False
ADBE     True
AES      True
AET      True
AFL      True
A        True
GAS      True
APD     False
ARG     False
AKAM     True
AA       True
ALXN    False
ATI      True
ALLE     True
AGN     False
ADS     False
ALL      True
ALTR     True
MO       True
AMZN    False
AEE      True
AEP      True
AXP      True
AIG      True
AMT      True
        ...
VIAB     True
V       False
VNO     False
VMC      True
WMT      True
WAG      True
DIS      True
WM       True
WAT     False
WLP     False
WFC      True
WDC      True
WU       True
WY       True
WHR     False
WFM      True
WIN      True
WEC      True
WYN      True
WYNN    False
XEL      True
XRX      True
XLNX     True
XL       True
XYL      True
YHOO     True
YUM      True
ZMH     False
ZION     True
ZTS      True
Name: Price, dtype: bool

In [58]:
sp500[sp500.Price < 100]

                             Sector  Price  Book Value
Symbol
ABT                     Health Care  39.60      15.573
ABBV                    Health Care  53.95       2.954
ACN          Information Technology  79.79       8.326
ADBE         Information Technology  64.30      13.262
AES                       Utilities  13.61       5.781
AET                     Health Care  76.39      40.021
AFL                      Financials  61.31      34.527
A                       Health Care  56.18      16.928
GAS                       Utilities  52.98      32.462
AKAM         Information Technology  53.65      15.193
AA                        Materials  13.52       9.670
ATI                       Materials  40.99      26.401
ALLE                    Industrials  52.46       0.000
ALL                      Financials  58.38      47.465
ALTR         Information Technology  33.31      11.026
MO                 Consumer Staples  40.68       2.072
AEE                       Utilities  38.64      26.847
AEP                       Utilities  51.41      33.635
AXP                      Financials  88.78      18.846
AIG                      Financials  53.60      71.775
AMT                      Financials  88.41       9.279
ABC                     Health Care  71.64       9.430
AME          Information Technology  52.49      13.341
APH                     Industrials  95.71      18.315
ADI          Information Technology  52.39      15.698
AON                      Financials  88.43      26.801
APA                          Energy  90.18      84.811
AIV                      Financials  31.24       6.331
AMAT         Information Technology  20.04       6.147
ADM                Consumer Staples  43.56      30.569
...                             ...    ...         ...
VLO                          Energy  54.54      37.335
VAR                     Health Care  80.92      16.141
VTR                      Financials  67.03      29.665
VRSN         Information Technology  49.92      -3.467
VZ      Telecommunications Services  49.74       3.069
VRTX                    Health Care  71.04       5.211
VFC          Consumer Discretionary  62.72      13.285
VIAB         Consumer Discretionary  84.99      10.253
VMC                       Materials  61.19      30.819
WMT                Consumer Staples  75.61      22.607
WAG                Consumer Staples  69.79      21.779
DIS          Consumer Discretionary  83.32      26.405
WM                      Industrials  43.37      12.330
WFC                      Financials  50.16      30.479
WDC          Information Technology  84.83      37.311
WU           Information Technology  15.77       1.981
WY                       Financials  30.87      11.690
WFM                Consumer Staples  37.78      10.867
WIN     Telecommunications Services   9.38       1.199
WEC                       Utilities  45.13      19.165
WYN          Consumer Discretionary  72.22      11.984
XEL                       Utilities  30.24      19.450
XRX          Information Technology  12.06      10.471
XLNX         Information Technology  46.03      10.247
XL                       Financials  32.47      37.451
XYL                     Industrials  38.42      12.127
YHOO         Information Technology  35.02      12.768
YUM          Consumer Discretionary  74.77       5.147
ZION                     Financials  28.43      30.191
ZTS                     Health Care  30.53       2.150

[407 rows x 3 columns]

In [59]:
sp500[(sp500.Price < 10) & (sp500.Price > 6)]['Price']

Symbol
HCBK    9.80
HBAN    9.10
SLM     8.82
WIN     9.38
Name: Price, dtype: float64

In [15]:
sp500[(sp500.Sector == 'Health Care') & (sp500.Price > 100.0)]

             Sector   Price  Book Value
Symbol
ACT     Health Care  213.77      55.188
ALXN    Health Care  162.30      13.628
AGN     Health Care  166.92      22.207
AMGN    Health Care  114.33      30.045
BCR     Health Care  146.62      26.964
BDX     Health Care  115.70      27.510
BIIB    Health Care  299.71      38.519
CELG    Health Care  150.13      11.200
HUM     Health Care  124.49      62.829
ISRG    Health Care  363.86      95.224
JNJ     Health Care  100.98      27.083
LH      Health Care  100.75      29.496
MCK     Health Care  183.75      36.892
PRGO    Health Care  138.63      63.962
REGN    Health Care  297.77      22.402
TMO     Health Care  115.74      51.212
WAT     Health Care  100.54      21.460
WLP     Health Care  108.82      86.358
ZMH     Health Care  101.84      37.181

In [62]:
sp500.loc[['ACT', 'MCK']][['Sector','Price']]

             Sector   Price
Symbol
ACT     Health Care  213.77
MCK     Health Care  183.75

In [16]:
newSp500 = sp500.rename(columns={'Book Value':'BookValue'})
newSp500

                             Sector   Price  BookValue
Symbol
MMM                     Industrials  141.14     26.668
ABT                     Health Care   39.60     15.573
ABBV                    Health Care   53.95      2.954
ACN          Information Technology   79.79      8.326
ACE                      Financials  102.91     86.897
ACT                     Health Care  213.77     55.188
ADBE         Information Technology   64.30     13.262
AES                       Utilities   13.61      5.781
AET                     Health Care   76.39     40.021
AFL                      Financials   61.31     34.527
A                       Health Care   56.18     16.928
GAS                       Utilities   52.98     32.462
APD                       Materials  118.74     34.723
ARG                       Materials  105.66     24.882
AKAM         Information Technology   53.65     15.193
AA                        Materials   13.52      9.670
ALXN                    Health Care  162.30     13.628
ATI                       Materials   40.99     26.401
ALLE                    Industrials   52.46      0.000
AGN                     Health Care  166.92     22.207
ADS          Information Technology  248.88     17.392
ALL                      Financials   58.38     47.465
ALTR         Information Technology   33.31     11.026
MO                 Consumer Staples   40.68      2.072
AMZN         Consumer Discretionary  312.24     22.452
AEE                       Utilities   38.64     26.847
AEP                       Utilities   51.41     33.635
AXP                      Financials   88.78     18.846
AIG                      Financials   53.60     71.775
AMT                      Financials   88.41      9.279
...                             ...     ...        ...
VIAB         Consumer Discretionary   84.99     10.253
V            Information Technology  212.07     43.391
VNO                      Financials  105.32     28.243
VMC                       Materials   61.19     30.819
WMT                Consumer Staples   75.61     22.607
WAG                Consumer Staples   69.79     21.779
DIS          Consumer Discretionary   83.32     26.405
WM                      Industrials   43.37     12.330
WAT                     Health Care  100.54     21.460
WLP                     Health Care  108.82     86.358
WFC                      Financials   50.16     30.479
WDC          Information Technology   84.83     37.311
WU           Information Technology   15.77      1.981
WY                       Financials   30.87     11.690
WHR          Consumer Discretionary  147.26     66.221
WFM                Consumer Staples   37.78     10.867
WIN     Telecommunications Services    9.38      1.199
WEC                       Utilities   45.13     19.165
WYN          Consumer Discretionary   72.22     11.984
WYNN         Consumer Discretionary  207.86     -0.719
XEL                       Utilities   30.24     19.450
XRX          Information Technology   12.06     10.471
XLNX         Information Technology   46.03     10.247
XL                       Financials   32.47     37.451
XYL                     Industrials   38.42     12.127
YHOO         Information Technology   35.02     12.768
YUM          Consumer Discretionary   74.77      5.147
ZMH                     Health Care  101.84     37.181
ZION                     Financials   28.43     30.191
ZTS                     Health Care   30.53      2.150

[500 rows x 3 columns]

In [64]:
sp500.columns

Index(['Sector', 'Price', 'Book Value'], dtype='object')

In [17]:
sp500_copy = sp500.copy()
sp500_copy['RoundedPrice'] = sp500.Price.round()
sp500_copy

                             Sector   Price  Book Value  RoundedPrice
Symbol
MMM                     Industrials  141.14      26.668         141.0
ABT                     Health Care   39.60      15.573          40.0
ABBV                    Health Care   53.95       2.954          54.0
ACN          Information Technology   79.79       8.326          80.0
ACE                      Financials  102.91      86.897         103.0
ACT                     Health Care  213.77      55.188         214.0
ADBE         Information Technology   64.30      13.262          64.0
AES                       Utilities   13.61       5.781          14.0
AET                     Health Care   76.39      40.021          76.0
AFL                      Financials   61.31      34.527          61.0
A                       Health Care   56.18      16.928          56.0
GAS                       Utilities   52.98      32.462          53.0
APD                       Materials  118.74      34.723         119.0
ARG                       Materials  105.66      24.882         106.0
AKAM         Information Technology   53.65      15.193          54.0
AA                        Materials   13.52       9.670          14.0
ALXN                    Health Care  162.30      13.628         162.0
ATI                       Materials   40.99      26.401          41.0
ALLE                    Industrials   52.46       0.000          52.0
AGN                     Health Care  166.92      22.207         167.0
ADS          Information Technology  248.88      17.392         249.0
ALL                      Financials   58.38      47.465          58.0
ALTR         Information Technology   33.31      11.026          33.0
MO                 Consumer Staples   40.68       2.072          41.0
AMZN         Consumer Discretionary  312.24      22.452         312.0
AEE                       Utilities   38.64      26.847          39.0
AEP                       Utilities   51.41      33.635          51.0
AXP                      Financials   88.78      18.846          89.0
AIG                      Financials   53.60      71.775          54.0
AMT                      Financials   88.41       9.279          88.0
...                             ...     ...         ...           ...
VIAB         Consumer Discretionary   84.99      10.253          85.0
V            Information Technology  212.07      43.391         212.0
VNO                      Financials  105.32      28.243         105.0
VMC                       Materials   61.19      30.819          61.0
WMT                Consumer Staples   75.61      22.607          76.0
WAG                Consumer Staples   69.79      21.779          70.0
DIS          Consumer Discretionary   83.32      26.405          83.0
WM                      Industrials   43.37      12.330          43.0
WAT                     Health Care  100.54      21.460         101.0
WLP                     Health Care  108.82      86.358         109.0
WFC                      Financials   50.16      30.479          50.0
WDC          Information Technology   84.83      37.311          85.0
WU           Information Technology   15.77       1.981          16.0
WY                       Financials   30.87      11.690          31.0
WHR          Consumer Discretionary  147.26      66.221         147.0
WFM                Consumer Staples   37.78      10.867          38.0
WIN     Telecommunications Services    9.38       1.199           9.0
WEC                       Utilities   45.13      19.165          45.0
WYN          Consumer Discretionary   72.22      11.984          72.0
WYNN         Consumer Discretionary  207.86      -0.719         208.0
XEL                       Utilities   30.24      19.450          30.0
XRX          Information Technology   12.06      10.471          12.0
XLNX         Information Technology   46.03      10.247          46.0
XL                       Financials   32.47      37.451          32.0
XYL                     Industrials   38.42      12.127          38.0
YHOO         Information Technology   35.02      12.768          35.0
YUM          Consumer Discretionary   74.77       5.147          75.0
ZMH                     Health Care  101.84      37.181         102.0
ZION                     Financials   28.43      30.191          28.0
ZTS                     Health Care   30.53       2.150          31.0

[500 rows x 4 columns]

In [18]:
sp500_copy = sp500.copy()
sp500_copy.insert(1, 'DoublePrice', sp500.Price * 2)
sp500_copy

                             Sector  DoublePrice   Price  Book Value
Symbol
MMM                     Industrials       282.28  141.14      26.668
ABT                     Health Care        79.20   39.60      15.573
ABBV                    Health Care       107.90   53.95       2.954
ACN          Information Technology       159.58   79.79       8.326
ACE                      Financials       205.82  102.91      86.897
ACT                     Health Care       427.54  213.77      55.188
ADBE         Information Technology       128.60   64.30      13.262
AES                       Utilities        27.22   13.61       5.781
AET                     Health Care       152.78   76.39      40.021
AFL                      Financials       122.62   61.31      34.527
A                       Health Care       112.36   56.18      16.928
GAS                       Utilities       105.96   52.98      32.462
APD                       Materials       237.48  118.74      34.723
ARG                       Materials       211.32  105.66      24.882
AKAM         Information Technology       107.30   53.65      15.193
AA                        Materials        27.04   13.52       9.670
ALXN                    Health Care       324.60  162.30      13.628
ATI                       Materials        81.98   40.99      26.401
ALLE                    Industrials       104.92   52.46       0.000
AGN                     Health Care       333.84  166.92      22.207
ADS          Information Technology       497.76  248.88      17.392
ALL                      Financials       116.76   58.38      47.465
ALTR         Information Technology        66.62   33.31      11.026
MO                 Consumer Staples        81.36   40.68       2.072
AMZN         Consumer Discretionary       624.48  312.24      22.452
AEE                       Utilities        77.28   38.64      26.847
AEP                       Utilities       102.82   51.41      33.635
AXP                      Financials       177.56   88.78      18.846
AIG                      Financials       107.20   53.60      71.775
AMT                      Financials       176.82   88.41       9.279
...                             ...          ...     ...         ...
VIAB         Consumer Discretionary       169.98   84.99      10.253
V            Information Technology       424.14  212.07      43.391
VNO                      Financials       210.64  105.32      28.243
VMC                       Materials       122.38   61.19      30.819
WMT                Consumer Staples       151.22   75.61      22.607
WAG                Consumer Staples       139.58   69.79      21.779
DIS          Consumer Discretionary       166.64   83.32      26.405
WM                      Industrials        86.74   43.37      12.330
WAT                     Health Care       201.08  100.54      21.460
WLP                     Health Care       217.64  108.82      86.358
WFC                      Financials       100.32   50.16      30.479
WDC          Information Technology       169.66   84.83      37.311
WU           Information Technology        31.54   15.77       1.981
WY                       Financials        61.74   30.87      11.690
WHR          Consumer Discretionary       294.52  147.26      66.221
WFM                Consumer Staples        75.56   37.78      10.867
WIN     Telecommunications Services        18.76    9.38       1.199
WEC                       Utilities        90.26   45.13      19.165
WYN          Consumer Discretionary       144.44   72.22      11.984
WYNN         Consumer Discretionary       415.72  207.86      -0.719
XEL                       Utilities        60.48   30.24      19.450
XRX          Information Technology        24.12   12.06      10.471
XLNX         Information Technology        92.06   46.03      10.247
XL                       Financials        64.94   32.47      37.451
XYL                     Industrials        76.84   38.42      12.127
YHOO         Information Technology        70.04   35.02      12.768
YUM          Consumer Discretionary       149.54   74.77       5.147
ZMH                     Health Care       203.68  101.84      37.181
ZION                     Financials        56.86   28.43      30.191
ZTS                     Health Care        61.06   30.53       2.150

[500 rows x 4 columns]

In [19]:
ss = sp500[:3].copy()
np.random.seed(123456)
ss.loc[:,'PER'] = pd.Series(np.random.normal(size=3), index=ss.index)
ss

             Sector   Price  Book Value       PER
Symbol
MMM     Industrials  141.14      26.668  0.469112
ABT     Health Care   39.60      15.573 -0.282863
ABBV    Health Care   53.95       2.954 -1.509059

In [20]:
new_column = pd.DataFrame({'RoundedPrice':sp500.Price.round()})
concatinate = pd.concat([sp500, new_column], axis=1)
concatinate.head()

                        Sector   Price  Book Value  RoundedPrice
Symbol
MMM                Industrials  141.14      26.668         141.0
ABT                Health Care   39.60      15.573          40.0
ABBV               Health Care   53.95       2.954          54.0
ACN     Information Technology   79.79       8.326          80.0
ACE                 Financials  102.91      86.897         103.0

In [21]:
copy = sp500.copy()
rounded_price = pd.DataFrame({'Price':sp500.Price.round()})
copy.Price = rounded_price.Price
copy.loc[:,'Price']=rounded_price.Price
copy.head()

                        Sector  Price  Book Value
Symbol
MMM                Industrials  141.0      26.668
ABT                Health Care   40.0      15.573
ABBV               Health Care   54.0       2.954
ACN     Information Technology   80.0       8.326
ACE                 Financials  103.0      86.897

In [22]:
copy = sp500.copy()
del copy['Book Value']
copy

                             Sector   Price
Symbol
MMM                     Industrials  141.14
ABT                     Health Care   39.60
ABBV                    Health Care   53.95
ACN          Information Technology   79.79
ACE                      Financials  102.91
ACT                     Health Care  213.77
ADBE         Information Technology   64.30
AES                       Utilities   13.61
AET                     Health Care   76.39
AFL                      Financials   61.31
A                       Health Care   56.18
GAS                       Utilities   52.98
APD                       Materials  118.74
ARG                       Materials  105.66
AKAM         Information Technology   53.65
AA                        Materials   13.52
ALXN                    Health Care  162.30
ATI                       Materials   40.99
ALLE                    Industrials   52.46
AGN                     Health Care  166.92
ADS          Information Technology  248.88
ALL                      Financials   58.38
ALTR         Information Technology   33.31
MO                 Consumer Staples   40.68
AMZN         Consumer Discretionary  312.24
AEE                       Utilities   38.64
AEP                       Utilities   51.41
AXP                      Financials   88.78
AIG                      Financials   53.60
AMT                      Financials   88.41
...                             ...     ...
VIAB         Consumer Discretionary   84.99
V            Information Technology  212.07
VNO                      Financials  105.32
VMC                       Materials   61.19
WMT                Consumer Staples   75.61
WAG                Consumer Staples   69.79
DIS          Consumer Discretionary   83.32
WM                      Industrials   43.37
WAT                     Health Care  100.54
WLP                     Health Care  108.82
WFC                      Financials   50.16
WDC          Information Technology   84.83
WU           Information Technology   15.77
WY                       Financials   30.87
WHR          Consumer Discretionary  147.26
WFM                Consumer Staples   37.78
WIN     Telecommunications Services    9.38
WEC                       Utilities   45.13
WYN          Consumer Discretionary   72.22
WYNN         Consumer Discretionary  207.86
XEL                       Utilities   30.24
XRX          Information Technology   12.06
XLNX         Information Technology   46.03
XL                       Financials   32.47
XYL                     Industrials   38.42
YHOO         Information Technology   35.02
YUM          Consumer Discretionary   74.77
ZMH                     Health Care  101.84
ZION                     Financials   28.43
ZTS                     Health Care   30.53

[500 rows x 2 columns]

In [23]:
copy = sp500.copy()
popped = copy.pop('Sector')
copy[:5]

         Price  Book Value
Symbol
MMM     141.14      26.668
ABT      39.60      15.573
ABBV     53.95       2.954
ACN      79.79       8.326
ACE     102.91      86.897

In [84]:
popped[:5]

Symbol
MMM                Industrials
ABT                Health Care
ABBV               Health Care
ACN     Information Technology
ACE                 Financials
Name: Sector, dtype: object

In [24]:
copy = sp500.copy()
afterdrop = copy.drop(['Sector'], axis=1)
afterdrop

         Price  Book Value
Symbol
MMM     141.14      26.668
ABT      39.60      15.573
ABBV     53.95       2.954
ACN      79.79       8.326
ACE     102.91      86.897
ACT     213.77      55.188
ADBE     64.30      13.262
AES      13.61       5.781
AET      76.39      40.021
AFL      61.31      34.527
A        56.18      16.928
GAS      52.98      32.462
APD     118.74      34.723
ARG     105.66      24.882
AKAM     53.65      15.193
AA       13.52       9.670
ALXN    162.30      13.628
ATI      40.99      26.401
ALLE     52.46       0.000
AGN     166.92      22.207
ADS     248.88      17.392
ALL      58.38      47.465
ALTR     33.31      11.026
MO       40.68       2.072
AMZN    312.24      22.452
AEE      38.64      26.847
AEP      51.41      33.635
AXP      88.78      18.846
AIG      53.60      71.775
AMT      88.41       9.279
...        ...         ...
VIAB     84.99      10.253
V       212.07      43.391
VNO     105.32      28.243
VMC      61.19      30.819
WMT      75.61      22.607
WAG      69.79      21.779
DIS      83.32      26.405
WM       43.37      12.330
WAT     100.54      21.460
WLP     108.82      86.358
WFC      50.16      30.479
WDC      84.83      37.311
WU       15.77       1.981
WY       30.87      11.690
WHR     147.26      66.221
WFM      37.78      10.867
WIN       9.38       1.199
WEC      45.13      19.165
WYN      72.22      11.984
WYNN    207.86      -0.719
XEL      30.24      19.450
XRX      12.06      10.471
XLNX     46.03      10.247
XL       32.47      37.451
XYL      38.42      12.127
YHOO     35.02      12.768
YUM      74.77       5.147
ZMH     101.84      37.181
ZION     28.43      30.191
ZTS      30.53       2.150

[500 rows x 2 columns]

In [25]:
df1 = sp500.iloc[0:3].copy()
df2 = sp500.iloc[[10,11,2]]
appended = df1.append(df2)
appended

             Sector   Price  Book Value
Symbol
MMM     Industrials  141.14      26.668
ABT     Health Care   39.60      15.573
ABBV    Health Care   53.95       2.954
A       Health Care   56.18      16.928
GAS       Utilities   52.98      32.462
ABBV    Health Care   53.95       2.954

In [26]:
df1 = sp500.iloc[0:3].copy()
df2 = sp500.iloc[[10,11,2]]
pd.concat([df1,df2])

             Sector   Price  Book Value
Symbol
MMM     Industrials  141.14      26.668
ABT     Health Care   39.60      15.573
ABBV    Health Care   53.95       2.954
A       Health Care   56.18      16.928
GAS       Utilities   52.98      32.462
ABBV    Health Care   53.95       2.954

In [28]:
df2_2 = df2.copy()
df2_2.insert(3, 'Foo', pd.Series(0, index=df2_2.index))
df2_2

             Sector  Price  Book Value  Foo
Symbol
A       Health Care  56.18      16.928    0
GAS       Utilities  52.98      32.462    0
ABBV    Health Care  53.95       2.954    0

In [29]:
pd.concat([df1, df2_2])

        Book Value  Foo   Price       Sector
Symbol
MMM         26.668  NaN  141.14  Industrials
ABT         15.573  NaN   39.60  Health Care
ABBV         2.954  NaN   53.95  Health Care
A           16.928  0.0   56.18  Health Care
GAS         32.462  0.0   52.98    Utilities
ABBV         2.954  0.0   53.95  Health Care

In [31]:
r = pd.concat([df1,df2_2], keys=['df1', 'df2_2'])
r

              Book Value  Foo   Price       Sector
      Symbol
df1   MMM         26.668  NaN  141.14  Industrials
      ABT         15.573  NaN   39.60  Health Care
      ABBV         2.954  NaN   53.95  Health Care
df2_2 A           16.928  0.0   56.18  Health Care
      GAS         32.462  0.0   52.98    Utilities
      ABBV         2.954  0.0   53.95  Health Care

In [32]:
ss = sp500[0:3].copy()
ss.loc['FOO'] = ['The Sector', 100, 110]
ss

             Sector   Price  Book Value
Symbol
MMM     Industrials  141.14      26.668
ABT     Health Care   39.60      15.573
ABBV    Health Care   53.95       2.954
FOO      The Sector  100.00     110.000

In [35]:
ss = sp500[0:5]
ss
after_drop = ss.drop(['ABT','ACN'])
after_drop

             Sector   Price  Book Value
Symbol
MMM     Industrials  141.14      26.668
ABBV    Health Care   53.95       2.954
ACE      Financials  102.91      86.897

In [40]:
selection = sp500.Price > 300
(len(selection),selection.sum())

(500, 10)

In [41]:
sp500_less_than_300 = sp500[-selection]
sp500_less_than_300

                             Sector   Price  Book Value
Symbol
MMM                     Industrials  141.14      26.668
ABT                     Health Care   39.60      15.573
ABBV                    Health Care   53.95       2.954
ACN          Information Technology   79.79       8.326
ACE                      Financials  102.91      86.897
ACT                     Health Care  213.77      55.188
ADBE         Information Technology   64.30      13.262
AES                       Utilities   13.61       5.781
AET                     Health Care   76.39      40.021
AFL                      Financials   61.31      34.527
A                       Health Care   56.18      16.928
GAS                       Utilities   52.98      32.462
APD                       Materials  118.74      34.723
ARG                       Materials  105.66      24.882
AKAM         Information Technology   53.65      15.193
AA                        Materials   13.52       9.670
ALXN                    Health Care  162.30      13.628
ATI                       Materials   40.99      26.401
ALLE                    Industrials   52.46       0.000
AGN                     Health Care  166.92      22.207
ADS          Information Technology  248.88      17.392
ALL                      Financials   58.38      47.465
ALTR         Information Technology   33.31      11.026
MO                 Consumer Staples   40.68       2.072
AEE                       Utilities   38.64      26.847
AEP                       Utilities   51.41      33.635
AXP                      Financials   88.78      18.846
AIG                      Financials   53.60      71.775
AMT                      Financials   88.41       9.279
AMP                      Financials  110.93      43.786
...                             ...     ...         ...
VIAB         Consumer Discretionary   84.99      10.253
V            Information Technology  212.07      43.391
VNO                      Financials  105.32      28.243
VMC                       Materials   61.19      30.819
WMT                Consumer Staples   75.61      22.607
WAG                Consumer Staples   69.79      21.779
DIS          Consumer Discretionary   83.32      26.405
WM                      Industrials   43.37      12.330
WAT                     Health Care  100.54      21.460
WLP                     Health Care  108.82      86.358
WFC                      Financials   50.16      30.479
WDC          Information Technology   84.83      37.311
WU           Information Technology   15.77       1.981
WY                       Financials   30.87      11.690
WHR          Consumer Discretionary  147.26      66.221
WFM                Consumer Staples   37.78      10.867
WIN     Telecommunications Services    9.38       1.199
WEC                       Utilities   45.13      19.165
WYN          Consumer Discretionary   72.22      11.984
WYNN         Consumer Discretionary  207.86      -0.719
XEL                       Utilities   30.24      19.450
XRX          Information Technology   12.06      10.471
XLNX         Information Technology   46.03      10.247
XL                       Financials   32.47      37.451
XYL                     Industrials   38.42      12.127
YHOO         Information Technology   35.02      12.768
YUM          Consumer Discretionary   74.77       5.147
ZMH                     Health Care  101.84      37.181
ZION                     Financials   28.43      30.191
ZTS                     Health Care   30.53       2.150

[490 rows x 3 columns]

In [5]:
df_i64 = pd.DataFrame(np.arange(10,20), index=np.arange(0,10))
df_i64.index

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [6]:
df_range = pd.DataFrame(np.arange(10,20))
df_range.index

RangeIndex(start=0, stop=10, step=1)

In [9]:
df_f64 = pd.DataFrame(np.arange(0,1000,5), np.arange(0.0, 100.0, 0.5))
df_f64.iloc[:5]

      0
0.0   0
0.5   5
1.0  10
1.5  15
2.0  20

In [10]:
df_f64.index

Float64Index([ 0.0,  0.5,  1.0,  1.5,  2.0,  2.5,  3.0,  3.5,  4.0,  4.5,
              ...
              95.0, 95.5, 96.0, 96.5, 97.0, 97.5, 98.0, 98.5, 99.0, 99.5],
             dtype='float64', length=200)

In [12]:
df_interval = pd.DataFrame({"A":[1 ,2, 3, 4]}, index = pd.IntervalIndex.from_breaks([0.0, 0.5, 1.0, 1.5, 2.0]))
df_interval

AttributeError: module 'pandas' has no attribute 'IntervalIndex'

In [15]:
rng = pd.date_range('9/5/2017', periods=5, freq='H')
ts = pd.Series(np.random.randn(len(rng)), index=rng)
ts

2017-09-05 00:00:00   -0.511792
2017-09-05 01:00:00   -2.619542
2017-09-05 02:00:00    1.717609
2017-09-05 03:00:00    2.629697
2017-09-05 04:00:00   -0.119034
Freq: H, dtype: float64

In [16]:
ts.index

DatetimeIndex(['2017-09-05 00:00:00', '2017-09-05 01:00:00',
               '2017-09-05 02:00:00', '2017-09-05 03:00:00',
               '2017-09-05 04:00:00'],
              dtype='datetime64[ns]', freq='H')

In [18]:
periods = pd.PeriodIndex(['2017-1', '2017-2','2017-3'], freq='M')
periods

PeriodIndex(['2017-01', '2017-02', '2017-03'], dtype='int64', freq='M')

In [20]:
periods_series = pd.Series(np.random.randn(len(periods)), index = periods)
periods_series

2017-01   -0.000833
2017-02    0.697592
2017-03   -0.053275
Freq: M, dtype: float64

In [21]:
date_times = pd.DatetimeIndex(pd.date_range('9/5/2017', periods=5,freq='H'))
date_times

DatetimeIndex(['2017-09-05 00:00:00', '2017-09-05 01:00:00',
               '2017-09-05 02:00:00', '2017-09-05 03:00:00',
               '2017-09-05 04:00:00'],
              dtype='datetime64[ns]', freq='H')

In [22]:
df_date_time = pd.DataFrame(np.arange(0, len(date_times)), index=date_times)
df_date_time

                     0
2017-09-05 00:00:00  0
2017-09-05 01:00:00  1
2017-09-05 02:00:00  2
2017-09-05 03:00:00  3
2017-09-05 04:00:00  4

In [24]:
sp500[:5]

                        Sector   Price  Book Value
Symbol
MMM                Industrials  141.14      26.668
ABT                Health Care   39.60      15.573
ABBV               Health Care   53.95       2.954
ACN     Information Technology   79.79       8.326
ACE                 Financials  102.91      86.897

In [27]:
remove_index_df = sp500.reset_index()
remove_index_df[:5]

  Symbol                  Sector   Price  Book Value
0    MMM             Industrials  141.14      26.668
1    ABT             Health Care   39.60      15.573
2   ABBV             Health Care   53.95       2.954
3    ACN  Information Technology   79.79       8.326
4    ACE              Financials  102.91      86.897

In [28]:
set_new_index_df = sp500.set_index('Sector')
set_new_index_df

                              Price  Book Value
Sector
Industrials                  141.14      26.668
Health Care                   39.60      15.573
Health Care                   53.95       2.954
Information Technology        79.79       8.326
Financials                   102.91      86.897
Health Care                  213.77      55.188
Information Technology        64.30      13.262
Utilities                     13.61       5.781
Health Care                   76.39      40.021
Financials                    61.31      34.527
Health Care                   56.18      16.928
Utilities                     52.98      32.462
Materials                    118.74      34.723
Materials                    105.66      24.882
Information Technology        53.65      15.193
Materials                     13.52       9.670
Health Care                  162.30      13.628
Materials                     40.99      26.401
Industrials                   52.46       0.000
Health Care                  166.92      22.207
Information Technology       248.88      17.392
Financials                    58.38      47.465
Information Technology        33.31      11.026
Consumer Staples              40.68       2.072
Consumer Discretionary       312.24      22.452
Utilities                     38.64      26.847
Utilities                     51.41      33.635
Financials                    88.78      18.846
Financials                    53.60      71.775
Financials                    88.41       9.279
...                             ...         ...
Consumer Discretionary        84.99      10.253
Information Technology       212.07      43.391
Financials                   105.32      28.243
Materials                     61.19      30.819
Consumer Staples              75.61      22.607
Consumer Staples              69.79      21.779
Consumer Discretionary        83.32      26.405
Industrials                   43.37      12.330
Health Care                  100.54      21.460
Health Care                  108.82      86.358
Financials                    50.16      30.479
Information Technology        84.83      37.311
Information Technology        15.77       1.981
Financials                    30.87      11.690
Consumer Discretionary       147.26      66.221
Consumer Staples              37.78      10.867
Telecommunications Services    9.38       1.199
Utilities                     45.13      19.165
Consumer Discretionary        72.22      11.984
Consumer Discretionary       207.86      -0.719
Utilities                     30.24      19.450
Information Technology        12.06      10.471
Information Technology        46.03      10.247
Financials                    32.47      37.451
Industrials                   38.42      12.127
Information Technology        35.02      12.768
Consumer Discretionary        74.77       5.147
Health Care                  101.84      37.181
Financials                    28.43      30.191
Health Care                   30.53       2.150

[500 rows x 2 columns]

In [29]:
reindexed = sp500.reindex(index=['MMM','ABBV','FOO'])
reindexed

             Sector   Price  Book Value
Symbol
MMM     Industrials  141.14      26.668
ABBV    Health Care   53.95       2.954
FOO             NaN     NaN         NaN

In [30]:
sp500[:5]

                        Sector   Price  Book Value
Symbol
MMM                Industrials  141.14      26.668
ABT                Health Care   39.60      15.573
ABBV               Health Care   53.95       2.954
ACN     Information Technology   79.79       8.326
ACE                 Financials  102.91      86.897

In [36]:
reindexed = sp500.reset_index()
multi_l_df = reindexed.set_index(['Sector', 'Symbol'])
multi_l_df[:10]

                                Price  Book Value
Sector                 Symbol
Industrials            MMM     141.14      26.668
Health Care            ABT      39.60      15.573
                       ABBV     53.95       2.954
Information Technology ACN      79.79       8.326
Financials             ACE     102.91      86.897
Health Care            ACT     213.77      55.188
Information Technology ADBE     64.30      13.262
Utilities              AES      13.61       5.781
Health Care            AET      76.39      40.021
Financials             AFL      61.31      34.527

In [37]:
type(multi_l_df.index)

pandas.indexes.multi.MultiIndex

In [38]:
len(multi_l_df.index.levels)

2

In [39]:
multi_l_df.index.levels[0]

Index(['Consumer Discretionary', 'Consumer Discretionary ', 'Consumer Staples',
       'Consumer Staples ', 'Energy', 'Financials', 'Health Care',
       'Industrials', 'Industries', 'Information Technology', 'Materials',
       'Telecommunications Services', 'Utilities'],
      dtype='object', name='Sector')

In [43]:
multi_l_df.index.get_level_values(0)

Index(['Industrials', 'Health Care', 'Health Care', 'Information Technology',
       'Financials', 'Health Care', 'Information Technology', 'Utilities',
       'Health Care', 'Financials',
       ...
       'Utilities', 'Information Technology', 'Information Technology',
       'Financials', 'Industrials', 'Information Technology',
       'Consumer Discretionary', 'Health Care', 'Financials', 'Health Care'],
      dtype='object', name='Sector', length=500)

In [49]:
multi_l_df.xs('Industrials', drop_level=False)[:5]

                     Price  Book Value
Sector      Symbol
Industrials MMM     141.14      26.668
            ALLE     52.46       0.000
            APH      95.71      18.315
            AVY      48.20      15.616
            BA      132.41      19.870

In [48]:
multi_l_df.xs('ALLE', level=1)

             Price  Book Value
Sector
Industrials  52.46         0.0

In [51]:
multi_l_df.xs('Industrials').xs('UPS')

Price         102.73
Book Value      6.79
Name: UPS, dtype: float64